language: node_js
node_js:
    - 12

script:
    - npm test
    - codecov -f coverage/*.json
    - npm i -g babel
    - npm run build
    - rsync -avh --progress ./types/ ./

notifications:
    slack: ${SLK}
