language: node_js
node_js:
    - 12
    - 11
    - 10
    - 9
    - 8
    - 7
    - 6

script:
    - npm test
    - codecov -f coverage/*.json
    - npm i -g babel
    - npm run build
    - rsync -avh --progress ./types/ ./

jobs:
    include:
        - stage: deploy docs
        script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd docs/documentation && npm is && GIT_USER="${GH_NAME}" npm run deploy

jobs:
    include:
        - stage: deploy
          on:
              branch: master
          deploy:
              provider: npm
              edge: true
              email: '$NPM_EMAIL'
              api_key: '$NPM_API_TOKEN'
